### ISSUE TITLE
Date fields in High Contrast mode

### ISSUE THREAD

**Issue by andrewvieau** [JakobChristensen/Sitecore.Rocks.Contrib#1]
I recently had a colorblind student who needed to use High Contrast mode in Visual Studio. Everything worked fine for the most part - the only exception was Date fields, which did not show any text.

**Comment by JakobChristensen** [comment]
I think you want to report this in the Sitecore.Rocks repository - not Sitecore.Rocks.Contrib.

**Comment by andrewvieau** [comment]
Done. Thanks!
